export const fonts = [
  // Bangers
  { name: "Bangers", src: "Bangers/Bangers-Regular.ttf", weight: 400, style: "normal" },

  // Bitter
  { name: "Bitter", src: "Bitter/static/Bitter-Black.ttf", weight: 900, style: "normal" },
  { name: "Bitter", src: "Bitter/static/Bitter-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Bitter", src: "Bitter/static/Bitter-Bold.ttf", weight: 700, style: "normal" },
  { name: "Bitter", src: "Bitter/static/Bitter-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Bitter", src: "Bitter/static/Bitter-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Bitter", src: "Bitter/static/Bitter-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Bitter", src: "Bitter/static/Bitter-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Bitter", src: "Bitter/static/Bitter-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Bitter", src: "Bitter/static/Bitter-Italic.ttf", weight: 400, style: "italic" },
  { name: "Bitter", src: "Bitter/static/Bitter-Light.ttf", weight: 300, style: "normal" },
  { name: "Bitter", src: "Bitter/static/Bitter-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Bitter", src: "Bitter/static/Bitter-Medium.ttf", weight: 500, style: "normal" },
  { name: "Bitter", src: "Bitter/static/Bitter-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Bitter", src: "Bitter/static/Bitter-Regular.ttf", weight: 400, style: "normal" },
  { name: "Bitter", src: "Bitter/static/Bitter-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Bitter", src: "Bitter/static/Bitter-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Bitter", src: "Bitter/static/Bitter-Thin.ttf", weight: 100, style: "normal" },
  { name: "Bitter", src: "Bitter/static/Bitter-ThinItalic.ttf", weight: 100, style: "italic" },

  // Chakra Petch
  { name: "Chakra Petch", src: "Chakra_Petch/ChakraPetch-Bold.ttf", weight: 700, style: "normal" },
  { name: "Chakra Petch", src: "Chakra_Petch/ChakraPetch-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Chakra Petch", src: "Chakra_Petch/ChakraPetch-Italic.ttf", weight: 400, style: "italic" },
  { name: "Chakra Petch", src: "Chakra_Petch/ChakraPetch-Light.ttf", weight: 300, style: "normal" },
  { name: "Chakra Petch", src: "Chakra_Petch/ChakraPetch-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Chakra Petch", src: "Chakra_Petch/ChakraPetch-Medium.ttf", weight: 500, style: "normal" },
  { name: "Chakra Petch", src: "Chakra_Petch/ChakraPetch-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Chakra Petch", src: "Chakra_Petch/ChakraPetch-Regular.ttf", weight: 400, style: "normal" },
  { name: "Chakra Petch", src: "Chakra_Petch/ChakraPetch-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Chakra Petch", src: "Chakra_Petch/ChakraPetch-SemiBoldItalic.ttf", weight: 600, style: "italic" },

  // Dancing Script
  { name: "Dancing Script", src: "Dancing_Script/static/DancingScript-Bold.ttf", weight: 700, style: "normal" },
  { name: "Dancing Script", src: "Dancing_Script/static/DancingScript-Medium.ttf", weight: 500, style: "normal" },
  { name: "Dancing Script", src: "Dancing_Script/static/DancingScript-Regular.ttf", weight: 400, style: "normal" },
  { name: "Dancing Script", src: "Dancing_Script/static/DancingScript-SemiBold.ttf", weight: 600, style: "normal" },

  // Kanit
  { name: "Kanit", src: "Kanit/Kanit-Black.ttf", weight: 900, style: "normal" },
  { name: "Kanit", src: "Kanit/Kanit-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Kanit", src: "Kanit/Kanit-Bold.ttf", weight: 700, style: "normal" },
  { name: "Kanit", src: "Kanit/Kanit-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Kanit", src: "Kanit/Kanit-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Kanit", src: "Kanit/Kanit-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Kanit", src: "Kanit/Kanit-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Kanit", src: "Kanit/Kanit-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Kanit", src: "Kanit/Kanit-Italic.ttf", weight: 400, style: "italic" },
  { name: "Kanit", src: "Kanit/Kanit-Light.ttf", weight: 300, style: "normal" },
  { name: "Kanit", src: "Kanit/Kanit-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Kanit", src: "Kanit/Kanit-Medium.ttf", weight: 500, style: "normal" },
  { name: "Kanit", src: "Kanit/Kanit-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Kanit", src: "Kanit/Kanit-Regular.ttf", weight: 400, style: "normal" },
  { name: "Kanit", src: "Kanit/Kanit-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Kanit", src: "Kanit/Kanit-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Kanit", src: "Kanit/Kanit-Thin.ttf", weight: 100, style: "normal" },
  { name: "Kanit", src: "Kanit/Kanit-ThinItalic.ttf", weight: 100, style: "italic" },

  // Lobster
  { name: "Lobster", src: "Lobster/Lobster-Regular.ttf", weight: 400, style: "normal" },

  // Montserrat
  { name: "Montserrat", src: "Montserrat/static/Montserrat-Black.ttf", weight: 900, style: "normal" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-Bold.ttf", weight: 700, style: "normal" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-Italic.ttf", weight: 400, style: "italic" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-Light.ttf", weight: 300, style: "normal" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-Medium.ttf", weight: 500, style: "normal" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-Regular.ttf", weight: 400, style: "normal" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-Thin.ttf", weight: 100, style: "normal" },
  { name: "Montserrat", src: "Montserrat/static/Montserrat-ThinItalic.ttf", weight: 100, style: "italic" },

  // Oswald
  { name: "Oswald", src: "Oswald/static/Oswald-Bold.ttf", weight: 700, style: "normal" },
  { name: "Oswald", src: "Oswald/static/Oswald-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Oswald", src: "Oswald/static/Oswald-Light.ttf", weight: 300, style: "normal" },
  { name: "Oswald", src: "Oswald/static/Oswald-Medium.ttf", weight: 500, style: "normal" },
  { name: "Oswald", src: "Oswald/static/Oswald-Regular.ttf", weight: 400, style: "normal" },
  { name: "Oswald", src: "Oswald/static/Oswald-SemiBold.ttf", weight: 600, style: "normal" },

  // Pacifico
  { name: "Pacifico", src: "Pacifico/Pacifico-Regular.ttf", weight: 400, style: "normal" },

  // Patrick Hand
  { name: "Patrick Hand", src: "Patrick_Hand/PatrickHand-Regular.ttf", weight: 400, style: "normal" },

  // Prompt
  { name: "Prompt", src: "Prompt/Prompt-Black.ttf", weight: 900, style: "normal" },
  { name: "Prompt", src: "Prompt/Prompt-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Prompt", src: "Prompt/Prompt-Bold.ttf", weight: 700, style: "normal" },
  { name: "Prompt", src: "Prompt/Prompt-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Prompt", src: "Prompt/Prompt-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Prompt", src: "Prompt/Prompt-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Prompt", src: "Prompt/Prompt-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Prompt", src: "Prompt/Prompt-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Prompt", src: "Prompt/Prompt-Italic.ttf", weight: 400, style: "italic" },
  { name: "Prompt", src: "Prompt/Prompt-Light.ttf", weight: 300, style: "normal" },
  { name: "Prompt", src: "Prompt/Prompt-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Prompt", src: "Prompt/Prompt-Medium.ttf", weight: 500, style: "normal" },
  { name: "Prompt", src: "Prompt/Prompt-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Prompt", src: "Prompt/Prompt-Regular.ttf", weight: 400, style: "normal" },
  { name: "Prompt", src: "Prompt/Prompt-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Prompt", src: "Prompt/Prompt-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Prompt", src: "Prompt/Prompt-Thin.ttf", weight: 100, style: "normal" },
  { name: "Prompt", src: "Prompt/Prompt-ThinItalic.ttf", weight: 100, style: "italic" },

  // Righteous
  { name: "Righteous", src: "Righteous/Righteous-Regular.ttf", weight: 400, style: "normal" },

  // Roboto
  { name: "Roboto", src: "Roboto/static/Roboto-Black.ttf", weight: 900, style: "normal" },
  { name: "Roboto", src: "Roboto/static/Roboto-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Roboto", src: "Roboto/static/Roboto-Bold.ttf", weight: 700, style: "normal" },
  { name: "Roboto", src: "Roboto/static/Roboto-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Roboto", src: "Roboto/static/Roboto-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Roboto", src: "Roboto/static/Roboto-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Roboto", src: "Roboto/static/Roboto-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Roboto", src: "Roboto/static/Roboto-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Roboto", src: "Roboto/static/Roboto-Italic.ttf", weight: 400, style: "italic" },
  { name: "Roboto", src: "Roboto/static/Roboto-Light.ttf", weight: 300, style: "normal" },
  { name: "Roboto", src: "Roboto/static/Roboto-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Roboto", src: "Roboto/static/Roboto-Medium.ttf", weight: 500, style: "normal" },
  { name: "Roboto", src: "Roboto/static/Roboto-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Roboto", src: "Roboto/static/Roboto-Regular.ttf", weight: 400, style: "normal" },
  { name: "Roboto", src: "Roboto/static/Roboto-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Roboto", src: "Roboto/static/Roboto-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Roboto", src: "Roboto/static/Roboto-Thin.ttf", weight: 100, style: "normal" },
  { name: "Roboto", src: "Roboto/static/Roboto-ThinItalic.ttf", weight: 100, style: "italic" },

  // Roboto Condensed
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-Black.ttf", weight: 900, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-Bold.ttf", weight: 700, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-Italic.ttf", weight: 400, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-Light.ttf", weight: 300, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-Medium.ttf", weight: 500, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-Regular.ttf", weight: 400, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-Thin.ttf", weight: 100, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto/static/Roboto_Condensed-ThinItalic.ttf", weight: 100, style: "italic" },

  // Roboto Semi Condensed
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-Black.ttf", weight: 900, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-Bold.ttf", weight: 700, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-Italic.ttf", weight: 400, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-Light.ttf", weight: 300, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-Medium.ttf", weight: 500, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-Regular.ttf", weight: 400, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-Thin.ttf", weight: 100, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto/static/Roboto_SemiCondensed-ThinItalic.ttf", weight: 100, style: "italic" },

  // Rock Salt
  { name: "Rock Salt", src: "Rock_Salt/RockSalt-Regular.ttf", weight: 400, style: "normal" },

  // Spectral SC
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-Bold.ttf", weight: 700, style: "normal" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-Italic.ttf", weight: 400, style: "italic" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-Light.ttf", weight: 300, style: "normal" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-Medium.ttf", weight: 500, style: "normal" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-Regular.ttf", weight: 400, style: "normal" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Spectral SC", src: "Spectral_SC/SpectralSC-SemiBoldItalic.ttf", weight: 600, style: "italic" }
];