export const fonts = [
  // Bangers
  { name: "Bangers", src: "Bangers-Regular.ttf", weight: 400, style: "normal" },

  // Bitter
  { name: "Bitter", src: "Bitter-Black.ttf", weight: 900, style: "normal" },
  { name: "Bitter", src: "Bitter-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Bitter", src: "Bitter-Bold.ttf", weight: 700, style: "normal" },
  { name: "Bitter", src: "Bitter-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Bitter", src: "Bitter-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Bitter", src: "Bitter-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Bitter", src: "Bitter-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Bitter", src: "Bitter-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Bitter", src: "Bitter-Italic.ttf", weight: 400, style: "italic" },
  { name: "Bitter", src: "Bitter-Light.ttf", weight: 300, style: "normal" },
  { name: "Bitter", src: "Bitter-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Bitter", src: "Bitter-Medium.ttf", weight: 500, style: "normal" },
  { name: "Bitter", src: "Bitter-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Bitter", src: "Bitter-Regular.ttf", weight: 400, style: "normal" },
  { name: "Bitter", src: "Bitter-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Bitter", src: "Bitter-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Bitter", src: "Bitter-Thin.ttf", weight: 100, style: "normal" },
  { name: "Bitter", src: "Bitter-ThinItalic.ttf", weight: 100, style: "italic" },

  // Chakra Petch
  { name: "Chakra Petch", src: "ChakraPetch-Bold.ttf", weight: 700, style: "normal" },
  { name: "Chakra Petch", src: "ChakraPetch-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Chakra Petch", src: "ChakraPetch-Italic.ttf", weight: 400, style: "italic" },
  { name: "Chakra Petch", src: "ChakraPetch-Light.ttf", weight: 300, style: "normal" },
  { name: "Chakra Petch", src: "ChakraPetch-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Chakra Petch", src: "ChakraPetch-Medium.ttf", weight: 500, style: "normal" },
  { name: "Chakra Petch", src: "ChakraPetch-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Chakra Petch", src: "ChakraPetch-Regular.ttf", weight: 400, style: "normal" },
  { name: "Chakra Petch", src: "ChakraPetch-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Chakra Petch", src: "ChakraPetch-SemiBoldItalic.ttf", weight: 600, style: "italic" },

  // Dancing Script
  { name: "Dancing Script", src: "DancingScript-Bold.ttf", weight: 700, style: "normal" },
  { name: "Dancing Script", src: "DancingScript-Medium.ttf", weight: 500, style: "normal" },
  { name: "Dancing Script", src: "DancingScript-Regular.ttf", weight: 400, style: "normal" },
  { name: "Dancing Script", src: "DancingScript-SemiBold.ttf", weight: 600, style: "normal" },

  // Kanit
  { name: "Kanit", src: "Kanit-Black.ttf", weight: 900, style: "normal" },
  { name: "Kanit", src: "Kanit-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Kanit", src: "Kanit-Bold.ttf", weight: 700, style: "normal" },
  { name: "Kanit", src: "Kanit-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Kanit", src: "Kanit-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Kanit", src: "Kanit-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Kanit", src: "Kanit-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Kanit", src: "Kanit-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Kanit", src: "Kanit-Italic.ttf", weight: 400, style: "italic" },
  { name: "Kanit", src: "Kanit-Light.ttf", weight: 300, style: "normal" },
  { name: "Kanit", src: "Kanit-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Kanit", src: "Kanit-Medium.ttf", weight: 500, style: "normal" },
  { name: "Kanit", src: "Kanit-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Kanit", src: "Kanit-Regular.ttf", weight: 400, style: "normal" },
  { name: "Kanit", src: "Kanit-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Kanit", src: "Kanit-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Kanit", src: "Kanit-Thin.ttf", weight: 100, style: "normal" },
  { name: "Kanit", src: "Kanit-ThinItalic.ttf", weight: 100, style: "italic" },

  // Lobster
  { name: "Lobster", src: "Lobster-Regular.ttf", weight: 400, style: "normal" },

  // Montserrat
  { name: "Montserrat", src: "Montserrat-Black.ttf", weight: 900, style: "normal" },
  { name: "Montserrat", src: "Montserrat-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Montserrat", src: "Montserrat-Bold.ttf", weight: 700, style: "normal" },
  { name: "Montserrat", src: "Montserrat-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Montserrat", src: "Montserrat-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Montserrat", src: "Montserrat-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Montserrat", src: "Montserrat-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Montserrat", src: "Montserrat-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Montserrat", src: "Montserrat-Italic.ttf", weight: 400, style: "italic" },
  { name: "Montserrat", src: "Montserrat-Light.ttf", weight: 300, style: "normal" },
  { name: "Montserrat", src: "Montserrat-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Montserrat", src: "Montserrat-Medium.ttf", weight: 500, style: "normal" },
  { name: "Montserrat", src: "Montserrat-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Montserrat", src: "Montserrat-Regular.ttf", weight: 400, style: "normal" },
  { name: "Montserrat", src: "Montserrat-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Montserrat", src: "Montserrat-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Montserrat", src: "Montserrat-Thin.ttf", weight: 100, style: "normal" },
  { name: "Montserrat", src: "Montserrat-ThinItalic.ttf", weight: 100, style: "italic" },

  // Oswald
  { name: "Oswald", src: "Oswald-Bold.ttf", weight: 700, style: "normal" },
  { name: "Oswald", src: "Oswald-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Oswald", src: "Oswald-Light.ttf", weight: 300, style: "normal" },
  { name: "Oswald", src: "Oswald-Medium.ttf", weight: 500, style: "normal" },
  { name: "Oswald", src: "Oswald-Regular.ttf", weight: 400, style: "normal" },
  { name: "Oswald", src: "Oswald-SemiBold.ttf", weight: 600, style: "normal" },

  // Pacifico
  { name: "Pacifico", src: "Pacifico-Regular.ttf", weight: 400, style: "normal" },

  // Patrick Hand
  { name: "Patrick Hand", src: "PatrickHand-Regular.ttf", weight: 400, style: "normal" },

  // Prompt
  { name: "Prompt", src: "Prompt-Black.ttf", weight: 900, style: "normal" },
  { name: "Prompt", src: "Prompt-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Prompt", src: "Prompt-Bold.ttf", weight: 700, style: "normal" },
  { name: "Prompt", src: "Prompt-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Prompt", src: "Prompt-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Prompt", src: "Prompt-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Prompt", src: "Prompt-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Prompt", src: "Prompt-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Prompt", src: "Prompt-Italic.ttf", weight: 400, style: "italic" },
  { name: "Prompt", src: "Prompt-Light.ttf", weight: 300, style: "normal" },
  { name: "Prompt", src: "Prompt-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Prompt", src: "Prompt-Medium.ttf", weight: 500, style: "normal" },
  { name: "Prompt", src: "Prompt-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Prompt", src: "Prompt-Regular.ttf", weight: 400, style: "normal" },
  { name: "Prompt", src: "Prompt-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Prompt", src: "Prompt-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Prompt", src: "Prompt-Thin.ttf", weight: 100, style: "normal" },
  { name: "Prompt", src: "Prompt-ThinItalic.ttf", weight: 100, style: "italic" },

  // Righteous
  { name: "Righteous", src: "Righteous-Regular.ttf", weight: 400, style: "normal" },

  // Roboto
  { name: "Roboto", src: "Roboto-Black.ttf", weight: 900, style: "normal" },
  { name: "Roboto", src: "Roboto-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Roboto", src: "Roboto-Bold.ttf", weight: 700, style: "normal" },
  { name: "Roboto", src: "Roboto-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Roboto", src: "Roboto-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Roboto", src: "Roboto-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Roboto", src: "Roboto-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Roboto", src: "Roboto-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Roboto", src: "Roboto-Italic.ttf", weight: 400, style: "italic" },
  { name: "Roboto", src: "Roboto-Light.ttf", weight: 300, style: "normal" },
  { name: "Roboto", src: "Roboto-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Roboto", src: "Roboto-Medium.ttf", weight: 500, style: "normal" },
  { name: "Roboto", src: "Roboto-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Roboto", src: "Roboto-Regular.ttf", weight: 400, style: "normal" },
  { name: "Roboto", src: "Roboto-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Roboto", src: "Roboto-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Roboto", src: "Roboto-Thin.ttf", weight: 100, style: "normal" },
  { name: "Roboto", src: "Roboto-ThinItalic.ttf", weight: 100, style: "italic" },

  // Roboto Condensed
  { name: "Roboto Condensed", src: "Roboto_Condensed-Black.ttf", weight: 900, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-Bold.ttf", weight: 700, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-Italic.ttf", weight: 400, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-Light.ttf", weight: 300, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-Medium.ttf", weight: 500, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-Regular.ttf", weight: 400, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-Thin.ttf", weight: 100, style: "normal" },
  { name: "Roboto Condensed", src: "Roboto_Condensed-ThinItalic.ttf", weight: 100, style: "italic" },

  // Roboto Semi Condensed
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-Black.ttf", weight: 900, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-BlackItalic.ttf", weight: 900, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-Bold.ttf", weight: 700, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-Italic.ttf", weight: 400, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-Light.ttf", weight: 300, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-Medium.ttf", weight: 500, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-Regular.ttf", weight: 400, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-SemiBoldItalic.ttf", weight: 600, style: "italic" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-Thin.ttf", weight: 100, style: "normal" },
  { name: "Roboto Semi Condensed", src: "Roboto_SemiCondensed-ThinItalic.ttf", weight: 100, style: "italic" },

  // Rock Salt
  { name: "Rock Salt", src: "RockSalt-Regular.ttf", weight: 400, style: "normal" },

  // Spectral SC
  { name: "Spectral SC", src: "SpectralSC-Bold.ttf", weight: 700, style: "normal" },
  { name: "Spectral SC", src: "SpectralSC-BoldItalic.ttf", weight: 700, style: "italic" },
  { name: "Spectral SC", src: "SpectralSC-ExtraBold.ttf", weight: 800, style: "normal" },
  { name: "Spectral SC", src: "SpectralSC-ExtraBoldItalic.ttf", weight: 800, style: "italic" },
  { name: "Spectral SC", src: "SpectralSC-ExtraLight.ttf", weight: 200, style: "normal" },
  { name: "Spectral SC", src: "SpectralSC-ExtraLightItalic.ttf", weight: 200, style: "italic" },
  { name: "Spectral SC", src: "SpectralSC-Italic.ttf", weight: 400, style: "italic" },
  { name: "Spectral SC", src: "SpectralSC-Light.ttf", weight: 300, style: "normal" },
  { name: "Spectral SC", src: "SpectralSC-LightItalic.ttf", weight: 300, style: "italic" },
  { name: "Spectral SC", src: "SpectralSC-Medium.ttf", weight: 500, style: "normal" },
  { name: "Spectral SC", src: "SpectralSC-MediumItalic.ttf", weight: 500, style: "italic" },
  { name: "Spectral SC", src: "SpectralSC-Regular.ttf", weight: 400, style: "normal" },
  { name: "Spectral SC", src: "SpectralSC-SemiBold.ttf", weight: 600, style: "normal" },
  { name: "Spectral SC", src: "SpectralSC-SemiBoldItalic.ttf", weight: 600, style: "italic" }
];